### ISSUE TITLE
Any steps necessary for mbdata users after MB’s PG12 update?

### ISSUE THREAD

**Issue by Freso** [lalinsky/mbdata#12]
[MusicBrainz updated their PostgreSQL version to 12](https://blog.metabrainz.org/2020/05/04/reminder-upgrading-to-postgresql-12-on-may-18-2020/) and have some [steps for downstream users already on PG12](https://blog.metabrainz.org/2020/05/18/postgresql-12-upgrade-instructions-for-musicbrainz-server/).

Do `mbdata` users need to take any special steps in this regard?

**Comment by heyoni** [comment]
I'm interested too. I'll check my logs and see if there are any errors at least.

**Comment by sfussenegger** [comment]
There are at least 2 SQL files in [PostgreSQL 12 Upgrade Instructions for MusicBrainz Server](https://blog.metabrainz.org/2020/05/18/postgresql-12-upgrade-instructions-for-musicbrainz-server/) that are missing. I've tried the steps outlines in `DEVELOPMENT.rst` for "Updating SQL files and models" but updating models fails:

```
# ./scripts/update_models.sh
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mbdata/mbdata/tools/genmodels.py", line 529, in <module>
    for line in generate_models_from_sql(tables, types, indexes):
  File "/mbdata/mbdata/tools/genmodels.py", line 464, in generate_models_from_sql
    for name, value in column_attributes.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

I’ve used this Dockerfile.dev to create a development environment:

```
FROM ubuntu:bionic

VOLUME /mbdata
WORKDIR /mbdata

RUN apt-get update && \
    apt-get install -y curl wget gnupg2 && \
    echo "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" > /etc/apt/sources.list.d/postgresql.list && \
    curl -s https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y \
      python3 \
      python3-dev \
      python3-pip \
      libpq-dev \
      gcc git vim virtualenv && \
    pip3 install sqlparse

ENTRYPOINT ["/bin/bash"]
```

Build:

```
docker build -t mbdata-dev -f Dockerfile.dev .
```

Usage:

```
docker run -ti --rm -v $PWD:/mbdata mbdata-dev
```

Reproduce (from DEVELOPMENT.rst):

```
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
python setup.py develop

./scripts/update_sql.sh
./scripts/update_models.sh
```

**Comment by Freso** [comment]
This was fixed with https://github.com/lalinsky/mbdata/pull/15
