### ISSUE TITLE
extras_required misspelled

### ISSUE THREAD

**Issue by mjpieters** [lalinsky/mbdata#13]
In `setup.py` we have:

https://github.com/lalinsky/mbdata/blob/42461d850e3ae47db3c95131ef1309215ce9fc72/setup.py#L31-L34

This presumably should be [`extras_require`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) instead. Note the extra `s`, *extras* is plural, not singular.

**Comment by lalinsky** [comment]
Ooops, that's an embarrassing error.

**Comment by mjpieters** [comment]
Any plans to cut a new release? It’s minor but let’s me remove the explicit dependency from our project config. :-)
