### ISSUE TITLE
Update for MBS 2021-05-17 schema change release

### ISSUE THREAD

**Issue by Freso** [lalinsky/mbdata#17]
https://blog.metabrainz.org/2021/05/18/musicbrainz-schema-change-release-2021-05-17-with-upgrade-instructions/

@yvanzo already has a branch with updates, not sure if it covers everything or not though, but it might work as a start if not: https://github.com/yvanzo/mbdata/tree/schema-change-2021-q2 – also not sure yet if he plans on making a PR of that or not. :)

**Comment by sfussenegger** [comment]
Similar to #12 last year the `./scripts/update_models.sh` step fails:

```
$ ./scripts/update_models.sh
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mbdata/mbdata/tools/genmodels.py", line 524, in <module>
    tables2, types2, indexes2 = parse_sql(sql)
  File "/mbdata/mbdata/tools/genmodels.py", line 173, in parse_sql
    tables.append(parse_create_table(statement, schema))
  File "/mbdata/mbdata/tools/genmodels.py", line 150, in parse_create_table
    table.columns.append(parse_create_table_column(column_clause, schema))
  File "/mbdata/mbdata/tools/genmodels.py", line 121, in parse_create_table_column
    column = Column(clause.get_name(), clause.get_type())
  File "/mbdata/mbdata/utils/sql.py", line 151, in get_type
    type = token.value
AttributeError: 'NoneType' object has no attribute 'value'
```

build can be reproduced using the development container suggested in #18

**Comment by Freso** [comment]
@sfussenegger Is that using Yvan’s branch, or the master branch here?

**Comment by sfussenegger** [comment]
> @sfussenegger Is that using Yvan’s branch, or the master branch here?

master branch as I've basically tried the "official" way of upgrading instead

**Comment by Freso** [comment]
Yeah, the official instructions are for people using the [musicbrainz-server (MBS) codebase](https://github.com/metabrainz/musicbrainz-server/), it doesn’t translate 1:1 to `mbdata`. You’ll notice a lot of reference to Perl scripts and what not there… :) E.g., "Perl 5.30 or later and NodeJS 16" are completely unnecessary for `mbdata`.

**Comment by sfussenegger** [comment]
No, not these official instructions. I'm talking about [mbdata/DEVELOPMENT.rst](https://github.com/lalinsky/mbdata/blob/master/DEVELOPMENT.rst)

**Comment by Freso** [comment]
> No, not these official instructions. I'm talking about [mbdata/DEVELOPMENT.rst](https://github.com/lalinsky/mbdata/blob/master/DEVELOPMENT.rst)

Those… don’t apply/relate to schema changes at all?

**Comment by sfussenegger** [comment]
They do, see [scripts/update_sql.sh](https://github.com/lalinsky/mbdata/blob/master/scripts/update_sql.sh). It copies and patches the latest SQL files from metabrainz/musicbrainz-server.

Also see #15 

> This brings mbdata up to par with MB Server again.
>
> - Fix Python-2-ism in gentools.py
> - Run the SQL and model generation steps
> - Update the fresh install instructions (new script to run)
> - Add notes on upgrading to PostgreSQL 12.

That's the "Run the SQL and model generation steps" part of the udpate.

**Comment by yvanzo** [comment]
I made a development branch on my repository for the sole needs of updating models for use with search index rebuilder.

The only part that was not handled by the script `update_models.sh` was adding support for first release date of recordings and releases. See the commit https://github.com/yvanzo/mbdata/commit/786acbfbe3de2cb2b79cdf9779637c1c5ba1c600#diff-3e3a2f69b9651c042895bd79a9c4e807c5b5d6326720a5e696296fb8f8d47fdc

It can possibly be implemented another way but that works for us.

**Comment by sfussenegger** [comment]
I've just tried running`./scripts/update_models.sh` with the updated `mbdata/tools/genmodels.py` from your commit but it still fails with the same error. Any idea what that might be caused by?
