### ISSUE TITLE
Instructions missing

### ISSUE THREAD

**Issue by marshalleq** [lalinsky/mbdata#2]
Instructions only say to 'pip install mbdata' then adjust mbslave.conf.default.  However this file does not appear to exist unless cloning the repository (according to my find query and general poking around).

**Comment by lalinsky** [comment]
Fixed in https://github.com/lalinsky/mbdata/commit/bdb9d31ce268afc690c3ce479cd1bb64fcc63d82

**Comment by marshalleq** [comment]
My apologies if it is my stupidity, but other than via cloning https://github.com/lalinsky/mbdata.git I don't know how to find this newly included mbslave file.  After running the pip install -U mbdata it doesn't seem to be anywhere.  When looking at the list of files that are uninstalled via pip uninstall mbdata, it is not listed.  Does the python package manager need time to receive the changes?

**Comment by marshalleq** [comment]
I've just seen this part - thanks.

curl https://raw.githubusercontent.com/lalinsky/mbdata/master/mbslave.conf.default -o mbslave.conf
vim mbslave.conf
