### ISSUE TITLE
How BIG is the database

### ISSUE THREAD

**Issue by aaronsql2019** [lalinsky/mbdata#25]
I find it funny when you go to the Apple App Store, and you aren't told how LARGE an app is. That is a KEY piece of information. When you get charged $1700 for a 1tb phone one of the MAIN DETERMINANTS I have in determining 'which games do I play' correlate to 'HOW LARGE IS THE GAME'?

Likewise, I don't have any idea how large this database is. That is the MAIN LIMITING FACTOR for me today. As a Database professional, I COULD install this on many different machines.

but I don't know, and I CANNOT decide what machine to install this on without having SOME ballpark of how large this app is. To be honest, I wish that GitHub would tell me 'How Large is a Project' before I choose to 'Download the Zip File' or connect to the project using Github Desktop.  If it's SMALL? A zip file is preferable.

Right now, I have utterly fallen in love with Music Brainz. I want to query the Database in PLAIN OLD SQL.  I can't do that until I google 'How Large Is the Music Brains Database'. Things should be easier than that. Google doesn't even return the SAME RESULTS for every person.

**Comment by kvognch** [comment]
> I find it funny when you go to the Apple App Store, and you aren't told how LARGE an app is. That is a KEY piece of information. When you get charged $1700 for a 1tb phone one of the MAIN DETERMINANTS I have in determining 'which games do I play' correlate to 'HOW LARGE IS THE GAME'?
> 
> Likewise, I don't have any idea how large this database is. That is the MAIN LIMITING FACTOR for me today. As a Database professional, I COULD install this on many different machines.
> 
> but I don't know, and I CANNOT decide what machine to install this on without having SOME ballpark of how large this app is. To be honest, I wish that GitHub would tell me 'How Large is a Project' before I choose to 'Download the Zip File' or connect to the project using Github Desktop. If it's SMALL? A zip file is preferable.
> 
> Right now, I have utterly fallen in love with Music Brainz. I want to query the Database in PLAIN OLD SQL. I can't do that until I google 'How Large Is the Music Brains Database'. Things should be easier than that. Google doesn't even return the SAME RESULTS for every person.

It seems to me that the database was about 11GB, but I could be wrong.

**Comment by lalinsky** [comment]
If you want to know how much data to download, have a look here: http://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/20210925-001928/

The most useful parts of the database, compressed, are about 4GB to download.

It needs about 18GB of disk space for PostgreSQL to import it.

**Comment by aaronsql2019** [comment]
thank you so much for this info. I wish that GITHUB would tell us how big a project / file was before downloading. And I wish that I knew more about how to use GitHub for Very Large Files.
