### ISSUE TITLE
Instructions incorrect?

### ISSUE THREAD

**Issue by marshalleq** [lalinsky/mbdata#3]
The instructions need to use 'mbslave' e.g. 

echo 'CREATE SCHEMA musicbrainz;' | mbslave psql -S

or 

mbslave psql -f CreateTables.sql

However, mbslave does not seem to exist anywhere or the instructions are not showing me clearly how to include this in my path / install it.  This worked very easily with mbslave, but does not seem to work with mbdata (which you referred me to in place of mbslave).

What am I missing?

Thanks.

**Comment by lalinsky** [comment]
If you run `pip install mbdata`, you should have the `mbslave` command in your path. Depending on how to you pip, it would be either in /usr/local/bin, ~/.local/bin or inside a virtualenv.

**Comment by marshalleq** [comment]
It exists if installing via pip install method (but other files don't seem to exist there).  However if cloning the repository into a folder, the mbslave does not seem to exist there like it did when cloning mbslave.  

It seems like the files in git clone https://github.com/lalinsky/mbdata.git /opt/mbdata are different to  pip install mbdata

**Comment by lalinsky** [comment]
You shouldn't clone the repository if you use pip. Anyway, I've updated the SQL scripts in the original mbslave repo, so you can use that in the meantime. I'll make sure the docs for mbdata are clearer.

**Comment by marshalleq** [comment]
OK thanks for that.
