### ISSUE TITLE
where are mbdump.tar.bz2 mbdump-derived.tar.bz2 on debian?

### ISSUE THREAD

**Issue by agawronski** [lalinsky/mbdata#34]
After downloading from:

http://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/

Where are these files?

mbslave import mbdump.tar.bz2 mbdump-derived.tar.bz2

ls -lah
total 60K
drwxrwxr-x   9 ubuntu ubuntu 4.0K Nov 21 04:35  .
drwxr-xr-x   8 ubuntu ubuntu 4.0K Nov 21 22:12  ..
drwxrwxr-x   2 ubuntu ubuntu 4.0K Nov 21 04:35  debian
drwxrwxr-x   2 ubuntu ubuntu 4.0K Nov 21 04:35  debian-cd
drwxrwxr-x   2 ubuntu ubuntu 4.0K Nov 21 04:35  debian-cdimage
drwxrwxr-x   2 ubuntu ubuntu 4.0K Nov 21 18:15  header-inc
drwxrwxr-x   2 ubuntu ubuntu 4.0K Nov 21 05:45  icons
-rw-rw-r--   1 ubuntu ubuntu 3.6K Nov 21 22:17  index.html
-rw-rw-r--   1 ubuntu ubuntu 3.6K Nov 22 07:14 'index.html?C=D;O=A'
-rw-rw-r--   1 ubuntu ubuntu 3.6K Nov 22 07:14 'index.html?C=M;O=A'
-rw-rw-r--   1 ubuntu ubuntu 3.6K Nov 22 07:14 'index.html?C=N;O=D'
-rw-rw-r--   1 ubuntu ubuntu 3.6K Nov 22 07:14 'index.html?C=S;O=A'
drwxrwxr-x   2 ubuntu ubuntu 4.0K Nov 21 04:35  lost+found
drwxrwxr-x 113 ubuntu ubuntu 4.0K Nov 21 22:17  pub
-rw-rw-r--   1 ubuntu ubuntu  754 May 13  2015  welcome.msg

**Comment by yvanzo** [comment]
It is likely under `pub/musicbrainz/data/fullexport/20211120-001843/`. If you don’t want all the HTML index files, use the FTP scheme instead: `ftp://ftp.musicbrainz.org/pub/musicbrainz/data/fullexport/20211120-001843/` (the timestamp changes every week).

**Comment by agawronski** [comment]
Thank you.
